# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KS_2s_2d_Layout.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1567, 928)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.main_frame = QtWidgets.QWidget(self.centralwidget)
        self.main_frame.setObjectName("main_frame")
        self.horizontalLayout.addWidget(self.main_frame)
        self.tabAnalyses_type = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabAnalyses_type.sizePolicy().hasHeightForWidth())
        self.tabAnalyses_type.setSizePolicy(sizePolicy)
        self.tabAnalyses_type.setMinimumSize(QtCore.QSize(330, 0))
        self.tabAnalyses_type.setObjectName("tabAnalyses_type")
        self.pushButton_file = QtWidgets.QPushButton(self.tabAnalyses_type)
        self.pushButton_file.setGeometry(QtCore.QRect(150, 10, 114, 32))
        self.pushButton_file.setObjectName("pushButton_file")
        self.label_files_iso = QtWidgets.QLabel(self.tabAnalyses_type)
        self.label_files_iso.setGeometry(QtCore.QRect(20, 15, 181, 21))
        self.label_files_iso.setObjectName("label_files_iso")
        self.pushButton_run = QtWidgets.QPushButton(self.tabAnalyses_type)
        self.pushButton_run.setGeometry(QtCore.QRect(30, 230, 241, 32))
        self.pushButton_run.setObjectName("pushButton_run")
        self.label_name_variables = QtWidgets.QLabel(self.tabAnalyses_type)
        self.label_name_variables.setGeometry(QtCore.QRect(20, 60, 291, 21))
        self.label_name_variables.setObjectName("label_name_variables")
        self.label_x = QtWidgets.QLabel(self.tabAnalyses_type)
        self.label_x.setGeometry(QtCore.QRect(20, 154, 31, 16))
        self.label_x.setObjectName("label_x")
        self.lineEdit_x_variable = QtWidgets.QLineEdit(self.tabAnalyses_type)
        self.lineEdit_x_variable.setGeometry(QtCore.QRect(50, 152, 113, 21))
        self.lineEdit_x_variable.setObjectName("lineEdit_x_variable")
        self.lineEdit_y_variable = QtWidgets.QLineEdit(self.tabAnalyses_type)
        self.lineEdit_y_variable.setGeometry(QtCore.QRect(50, 180, 113, 21))
        self.lineEdit_y_variable.setText("")
        self.lineEdit_y_variable.setObjectName("lineEdit_y_variable")
        self.label_y = QtWidgets.QLabel(self.tabAnalyses_type)
        self.label_y.setGeometry(QtCore.QRect(20, 182, 31, 16))
        self.label_y.setObjectName("label_y")
        self.label_name_variables_pop1 = QtWidgets.QLabel(self.tabAnalyses_type)
        self.label_name_variables_pop1.setGeometry(QtCore.QRect(20, 90, 291, 21))
        self.label_name_variables_pop1.setObjectName("label_name_variables_pop1")
        self.label_name_variables_pop2 = QtWidgets.QLabel(self.tabAnalyses_type)
        self.label_name_variables_pop2.setGeometry(QtCore.QRect(20, 120, 291, 21))
        self.label_name_variables_pop2.setObjectName("label_name_variables_pop2")
        self.lineEdit_name_pop1 = QtWidgets.QLineEdit(self.tabAnalyses_type)
        self.lineEdit_name_pop1.setGeometry(QtCore.QRect(130, 90, 113, 21))
        self.lineEdit_name_pop1.setObjectName("lineEdit_name_pop1")
        self.lineEdit_name_pop2 = QtWidgets.QLineEdit(self.tabAnalyses_type)
        self.lineEdit_name_pop2.setGeometry(QtCore.QRect(130, 120, 113, 21))
        self.lineEdit_name_pop2.setObjectName("lineEdit_name_pop2")
        self.horizontalLayout.addWidget(self.tabAnalyses_type)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1567, 24))
        self.menubar.setObjectName("menubar")
        self.menuInput_data = QtWidgets.QMenu(self.menubar)
        self.menuInput_data.setObjectName("menuInput_data")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout_MatriSIMS = QtWidgets.QAction(MainWindow)
        self.actionAbout_MatriSIMS.setObjectName("actionAbout_MatriSIMS")
        self.actionPreferences = QtWidgets.QAction(MainWindow)
        self.actionPreferences.setObjectName("actionPreferences")
        self.actionNew_project = QtWidgets.QAction(MainWindow)
        self.actionNew_project.setObjectName("actionNew_project")
        self.actionOpen_project = QtWidgets.QAction(MainWindow)
        self.actionOpen_project.setObjectName("actionOpen_project")
        self.actionSave_project = QtWidgets.QAction(MainWindow)
        self.actionSave_project.setObjectName("actionSave_project")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionResiduals = QtWidgets.QAction(MainWindow)
        self.actionResiduals.setObjectName("actionResiduals")
        self.actionAdvanced_statistics = QtWidgets.QAction(MainWindow)
        self.actionAdvanced_statistics.setObjectName("actionAdvanced_statistics")
        self.actionStandards = QtWidgets.QAction(MainWindow)
        self.actionStandards.setObjectName("actionStandards")
        self.actionResiduals_2 = QtWidgets.QAction(MainWindow)
        self.actionResiduals_2.setEnabled(False)
        self.actionResiduals_2.setObjectName("actionResiduals_2")
        self.actionAll_data = QtWidgets.QAction(MainWindow)
        self.actionAll_data.setObjectName("actionAll_data")
        self.actionStandard_data = QtWidgets.QAction(MainWindow)
        self.actionStandard_data.setObjectName("actionStandard_data")
        self.actionSample_data = QtWidgets.QAction(MainWindow)
        self.actionSample_data.setObjectName("actionSample_data")
        self.actionWhole_session = QtWidgets.QAction(MainWindow)
        self.actionWhole_session.setObjectName("actionWhole_session")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionOptics_and_primary = QtWidgets.QAction(MainWindow)
        self.actionOptics_and_primary.setObjectName("actionOptics_and_primary")
        self.actionInput_data = QtWidgets.QAction(MainWindow)
        self.actionInput_data.setObjectName("actionInput_data")
        self.actionData = QtWidgets.QAction(MainWindow)
        self.actionData.setObjectName("actionData")
        self.actionStatistics = QtWidgets.QAction(MainWindow)
        self.actionStatistics.setObjectName("actionStatistics")
        self.actionDeadtime = QtWidgets.QAction(MainWindow)
        self.actionDeadtime.setEnabled(False)
        self.actionDeadtime.setObjectName("actionDeadtime")
        self.actionBackground = QtWidgets.QAction(MainWindow)
        self.actionBackground.setEnabled(False)
        self.actionBackground.setObjectName("actionBackground")
        self.actionChange_of_cycles = QtWidgets.QAction(MainWindow)
        self.actionChange_of_cycles.setEnabled(False)
        self.actionChange_of_cycles.setObjectName("actionChange_of_cycles")
        self.actionReset = QtWidgets.QAction(MainWindow)
        self.actionReset.setObjectName("actionReset")
        self.actionSave_figure = QtWidgets.QAction(MainWindow)
        self.actionSave_figure.setObjectName("actionSave_figure")
        self.menuInput_data.addAction(self.actionData)
        self.menuInput_data.addAction(self.actionSave_figure)
        self.menubar.addAction(self.menuInput_data.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_file.setText(_translate("MainWindow", "Select"))
        self.label_files_iso.setText(_translate("MainWindow", "Select the input file:"))
        self.pushButton_run.setText(_translate("MainWindow", "Run!"))
        self.label_name_variables.setText(_translate("MainWindow", "Name of variables"))
        self.label_x.setText(_translate("MainWindow", "x"))
        self.label_y.setText(_translate("MainWindow", "y"))
        self.label_name_variables_pop1.setText(_translate("MainWindow", "1st population:"))
        self.label_name_variables_pop2.setText(_translate("MainWindow", "2nd population:"))
        self.menuInput_data.setTitle(_translate("MainWindow", "Output"))
        self.actionAbout_MatriSIMS.setText(_translate("MainWindow", "About MatriSIMS"))
        self.actionPreferences.setText(_translate("MainWindow", "Preferences"))
        self.actionNew_project.setText(_translate("MainWindow", "New project"))
        self.actionOpen_project.setText(_translate("MainWindow", "Open project"))
        self.actionSave_project.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionResiduals.setText(_translate("MainWindow", "Residuals"))
        self.actionAdvanced_statistics.setText(_translate("MainWindow", "Advanced statistics"))
        self.actionStandards.setText(_translate("MainWindow", "Standards"))
        self.actionResiduals_2.setText(_translate("MainWindow", "Residuals"))
        self.actionAll_data.setText(_translate("MainWindow", "All data"))
        self.actionStandard_data.setText(_translate("MainWindow", "Standard data"))
        self.actionSample_data.setText(_translate("MainWindow", "Sample data"))
        self.actionWhole_session.setText(_translate("MainWindow", "Whole session"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionOptics_and_primary.setText(_translate("MainWindow", "Tutorial"))
        self.actionInput_data.setText(_translate("MainWindow", "Input data"))
        self.actionData.setText(_translate("MainWindow", "p-value"))
        self.actionStatistics.setText(_translate("MainWindow", "Statistics"))
        self.actionDeadtime.setText(_translate("MainWindow", "Deadtime"))
        self.actionBackground.setText(_translate("MainWindow", "Background"))
        self.actionChange_of_cycles.setText(_translate("MainWindow", "Change # of cycles"))
        self.actionReset.setText(_translate("MainWindow", "Reset"))
        self.actionSave_figure.setText(_translate("MainWindow", "Save figure"))
